In [5]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [6]:
df=pd.read_csv("heart.csv")

In [7]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [9]:
df.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

             thal      target  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [10]:
df.sort_values(by="age")

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
72    29    1   1       130   204    0        0      202      0      0.0   
58    34    1   3       118   182    0        0      174      0      0.0   
125   34    0   1       118   210    0        1      192      0      0.7   
239   35    1   0       126   282    0        0      156      1      0.0   
65    35    0   0       138   183    0        1      182      0      1.4   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
60    71    0   2       110   265    1        0      130      0      0.0   
151   71    0   0       112   149    0        1      125      0      1.6   
129   74    0   1       120   269    0        0      121      1      0.2   
144   76    0   2       140   197    0        2      116      0      1.1   
238   77    1   0       125   304    0        0      162      1      0.0   

     slope  ca  thal  target  
72       2   0     2       1  
58       2   0     2       1  
125      2   0     2       1  
239      2   0     3       0  
65       2   0     2       1  
..     ...  ..   ...     ...  
60       2   1     2       1  
151      1   0     2       1  
129      2   1     2       1  
144      1   0     2       1  
238      2   3     2       0  

[303 rows x 14 columns]

In [11]:
df["rank"]=df["age"].rank()
print(df["rank"])

0      248.0
1        8.5
2       24.5
3      158.0
4      172.0
       ...  
298    172.0
299     60.5
300    288.5
301    172.0
302    172.0
Name: rank, Length: 303, dtype: float64


In [12]:
df.nunique()

age          41
sex           2
cp            4
trestbps     49
chol        152
fbs           2
restecg       3
thalach      91
exang         2
oldpeak      40
slope         3
ca            5
thal          4
target        2
rank         41
dtype: int64

In [13]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
rank        0
dtype: int64

In [14]:
df.shape

(303, 15)

In [15]:
df.drop_duplicates()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target   rank  
0        0   0     1       1  248.0  
1        0   0     2       1    8.5  
2        2   0     2       1   24.5  
3        2   0     2       1  158.0  
4        2   0     2       1  172.0  
..     ...  ..   ...     ...    ...  
298      1   0     3       0  172.0  
299      1   0     3       0   60.5  
300      1   2     3       0  288.5  
301      1   1     3       0  172.0  
302      1   1     2       0  172.0  

[302 rows x 15 columns]

In [16]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target', 'rank'],
      dtype='object')

In [17]:
df.describe().T

count        mean        std    min    25%    50%    75%    max
age       303.0   54.366337   9.082101   29.0   47.5   55.0   61.0   77.0
sex       303.0    0.683168   0.466011    0.0    0.0    1.0    1.0    1.0
cp        303.0    0.966997   1.032052    0.0    0.0    1.0    2.0    3.0
trestbps  303.0  131.623762  17.538143   94.0  120.0  130.0  140.0  200.0
chol      303.0  246.264026  51.830751  126.0  211.0  240.0  274.5  564.0
fbs       303.0    0.148515   0.356198    0.0    0.0    0.0    0.0    1.0
restecg   303.0    0.528053   0.525860    0.0    0.0    1.0    1.0    2.0
thalach   303.0  149.646865  22.905161   71.0  133.5  153.0  166.0  202.0
exang     303.0    0.326733   0.469794    0.0    0.0    0.0    1.0    1.0
oldpeak   303.0    1.039604   1.161075    0.0    0.0    0.8    1.6    6.2
slope     303.0    1.399340   0.616226    0.0    1.0    1.0    2.0    2.0
ca        303.0    0.729373   1.022606    0.0    0.0    0.0    1.0    4.0
thal      303.0    2.313531   0.612277    0.0    2.0    2.0    3.0    3.0
target    303.0    0.544554   0.498835    0.0    0.0    1.0    1.0    1.0
rank      303.0  152.000000  87.555120    1.0   77.0  148.5  228.5  303.0

In [18]:
df["sex"].unique()

array([1, 0], dtype=int64)

In [19]:
df["sex"].value_counts()

1    207
0     96
Name: sex, dtype: int64

# KNN Algorithm

In [20]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


In [21]:
X=df.drop('target',axis=1)
y=df['target']

In [22]:
#Standardize the features
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)

In [23]:
#Split the data
X_train,X_test,y_train,y_test=train_test_split(X_scaled,y,test_size=0.3,random_state=42)

In [24]:
#Initialize the KNN model
knn=KNeighborsClassifier(n_neighbors=5)

#Train the model
knn.fit(X_train,y_train)

#Make predictions
y_pred=knn.predict(X_test)

In [25]:
#Evaluate the accuracy
accuracy=accuracy_score(y_test,y_pred)
print(f'Accuracy:{accuracy:.2f}')

#Classification report
print(classification_report(y_test,y_pred))

#Confusion matrix
print(confusion_matrix(y_test,y_pred))

Accuracy:0.85
              precision    recall  f1-score   support

           0       0.81      0.85      0.83        41
           1       0.88      0.84      0.86        50

    accuracy                           0.85        91
   macro avg       0.84      0.85      0.85        91
weighted avg       0.85      0.85      0.85        91

[[35  6]
 [ 8 42]]


# Support Vector Machine

In [47]:
from sklearn.svm import SVC

In [48]:
svm=SVC(kernel='linear')

#Train the model
svm.fit(X_train,y_train)

#Make Prediction
y_pred=svm.predict(X_test)

In [52]:
#Evaluate the accuracy
accuracy=accuracy_score(y_test,y_pred)
print(f'Accuracy:{accuracy:.2f}')

#classification report
print(classification_report(y_test,y_pred))

#confusion matrix
print(confusion_matrix(y_test,y_pred))

Accuracy:0.82
              precision    recall  f1-score   support

           0       0.80      0.80      0.80        41
           1       0.84      0.84      0.84        50

    accuracy                           0.82        91
   macro avg       0.82      0.82      0.82        91
weighted avg       0.82      0.82      0.82        91

[[33  8]
 [ 8 42]]


# RANDOM FOREST

In [53]:
from sklearn.ensemble import RandomForestClassifier

In [54]:
#Initialize the random forest classifier
rf=RandomForestClassifier(n_estimators=100,random_state=42)

In [59]:
#Train the model
rf.fit(X_train,y_train)

#Make prediction
y_pred=rf.predict(X_test)

In [60]:
#Evaluate the accuracy
accuracy=accuracy_score(y_test,y_pred)
print(f'Accuracy:{accuracy:.2f}')

#classification report
print(classification_report(y_test,y_pred))

#confusion matrix
print(confusion_matrix(y_test,y_pred))

Accuracy:0.82
              precision    recall  f1-score   support

           0       0.80      0.80      0.80        41
           1       0.84      0.84      0.84        50

    accuracy                           0.82        91
   macro avg       0.82      0.82      0.82        91
weighted avg       0.82      0.82      0.82        91

[[33  8]
 [ 8 42]]


# Decision Tree

In [61]:
from sklearn.tree import DecisionTreeClassifier

In [62]:
#Initialize the Decision Tree Model
dt=DecisionTreeClassifier(random_state=42)

In [64]:
#train the model
dt.fit(X_train,y_train)

#make predictions
y_pred=dt.predict(X_test)

In [66]:
#Evaluate the accuracy
accuracy=accuracy_score(y_test,y_pred)
print(f'Accuracy:{accuracy:.2f}')

#classification report
print(classification_report(y_test,y_pred))

#confusion matrix
print(confusion_matrix(y_test,y_pred))

Accuracy:0.75
              precision    recall  f1-score   support

           0       0.69      0.80      0.74        41
           1       0.81      0.70      0.75        50

    accuracy                           0.75        91
   macro avg       0.75      0.75      0.75        91
weighted avg       0.76      0.75      0.75        91

[[33  8]
 [15 35]]


# Logistic regression

In [68]:
from sklearn.linear_model import LogisticRegression

In [69]:
lr=LogisticRegression(max_iter=1000,random_state=42)

In [71]:
#train the model
lr.fit(X_train,y_train)

#make predicitions
y_pred=lr.predict(X_test)

In [72]:
#Evaluate the accuracy
accuracy=accuracy_score(y_test,y_pred)
print(f'Accuracy:{accuracy:.2f}')

#classification report
print(classification_report(y_test,y_pred))

#confusion matrix
print(confusion_matrix(y_test,y_pred))

Accuracy:0.81
              precision    recall  f1-score   support

           0       0.80      0.78      0.79        41
           1       0.82      0.84      0.83        50

    accuracy                           0.81        91
   macro avg       0.81      0.81      0.81        91
weighted avg       0.81      0.81      0.81        91

[[32  9]
 [ 8 42]]


In [84]:
# Assuming you have stored the accuracy for each model in variables
knn_accuracy = 0.85  # Example values, replace with actual results
svm_accuracy = 0.82
rf_accuracy = 0.82
dt_accuracy = 0.75
lr_accuracy = 0.81


# Store the accuracies in a dictionary
accuracies = {
    'KNN': knn_accuracy,
    'SVM': svm_accuracy,
    'Random Forest': rf_accuracy,
    'Decision Tree': dt_accuracy,
    'Logistic Regression': lr_accuracy
}

# Find the best algorithm
best_algorithm = max(accuracies, key=accuracies.get)
best_accuracy = accuracies[best_algorithm]

print(f"The best algorithm is {best_algorithm} with an accuracy of {best_accuracy:.2f}")

The best algorithm is KNN with an accuracy of 0.85
