In [19]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
#support vector machine
from sklearn.svm import SVC

In [20]:
df=pd.read_csv("WineQT.csv")

In [21]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  Id  
0      9.4        5   0  
1      9.8        5   1  
2      9.8        5   2  
3      9.8        6   3  
4      9.4        5   4

In [22]:
X=df.drop('quality',axis=1)
y=df['quality']

In [23]:
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)

In [24]:
#split the data
X_train,X_test,y_train,y_test=train_test_split(X_scaled,y,test_size=0.3,random_state=42)

In [25]:
#KNN 
knn=KNeighborsClassifier(n_neighbors=5)

#train the model
knn.fit(X_train,y_train)

#make predictions
y_pred=knn.predict(X_test)

In [26]:
#evaluate the accuracy
accuracy=accuracy_score(y_test,y_pred)
print(f'Accuracy: {accuracy:.2f}')

#classification report
print(classification_report(y_test,y_pred))

#confusion matrix
print(confusion_matrix(y_test,y_pred))

Accuracy: 0.54
              precision    recall  f1-score   support

           4       0.00      0.00      0.00         9
           5       0.58      0.66      0.62       143
           6       0.52      0.53      0.53       146
           7       0.45      0.32      0.37        41
           8       0.00      0.00      0.00         4

    accuracy                           0.54       343
   macro avg       0.31      0.30      0.30       343
weighted avg       0.52      0.54      0.53       343

[[ 0  7  2  0  0]
 [ 2 95 44  2  0]
 [ 1 54 77 14  0]
 [ 0  6 22 13  0]
 [ 0  2  2  0  0]]


C:\Users\Sneha Rajput\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Sneha Rajput\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Sneha Rajput\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [29]:
#SUPPORT VECTOR MACHINE
svm=SVC(kernel='linear')

#train the model
svm.fit(X_train,y_train)

#make prediction
y_pred=svm.predict(X_test)

In [31]:
#evaluate the accuracy
accuracy=accuracy_score(y_test,y_pred)
print(f'Accuracy: {accuracy:.2f}')

#classification report
print(classification_report(y_test,y_pred))

#confusion matrix
print(confusion_matrix(y_test,y_pred))

Accuracy: 0.60
              precision    recall  f1-score   support

           4       0.00      0.00      0.00         9
           5       0.65      0.75      0.69       143
           6       0.57      0.64      0.60       146
           7       0.40      0.15      0.21        41
           8       0.00      0.00      0.00         4

    accuracy                           0.60       343
   macro avg       0.32      0.31      0.30       343
weighted avg       0.56      0.60      0.57       343

[[  0   6   3   0   0]
 [  0 107  34   2   0]
 [  0  48  93   5   0]
 [  0   4  31   6   0]
 [  0   0   2   2   0]]


C:\Users\Sneha Rajput\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Sneha Rajput\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Sneha Rajput\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [32]:
#RANDOM FOREST
from sklearn.ensemble import RandomForestClassifier

In [33]:
#Initialize the random forest model
rf=RandomForestClassifier(n_estimators=100,random_state=42)

#train the model
rf.fit(X_train,y_train)

#make prediction
y_pred=rf.predict(X_test)

In [34]:
#evaluate the accuracy
accuracy=accuracy_score(y_test,y_pred)
print(f'Accuracy:{accuracy:.2f}')

#classifier report
print(classification_report(y_test,y_pred))

#confusion matrix
print(confusion_matrix(y_test,y_pred))

Accuracy:0.65
              precision    recall  f1-score   support

           4       0.00      0.00      0.00         9
           5       0.68      0.73      0.70       143
           6       0.61      0.66      0.63       146
           7       0.71      0.54      0.61        41
           8       1.00      0.25      0.40         4

    accuracy                           0.65       343
   macro avg       0.60      0.43      0.47       343
weighted avg       0.64      0.65      0.64       343

[[  0   7   2   0   0]
 [  0 104  37   2   0]
 [  0  43  96   7   0]
 [  0   0  19  22   0]
 [  0   0   3   0   1]]


C:\Users\Sneha Rajput\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Sneha Rajput\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Sneha Rajput\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [35]:
#LOGISTIC REGRESSION
from sklearn.linear_model import LogisticRegression

#initialize the logistic regression model
lr=LogisticRegression(max_iter=1000,random_state=42)

#train the model
lr.fit(X_train,y_train)

#make prediction
y_pred=lr.predict(X_test)


In [36]:
#Evaluate the accuracy
accuracy=accuracy_score(y_test,y_pred)
print(f'Accuracy:{accuracy:.2f}')

#classification report
print(classification_report(y_test,y_pred))

#confusion matrix
print(confusion_matrix(y_test,y_pred))

Accuracy:0.63
              precision    recall  f1-score   support

           4       0.00      0.00      0.00         9
           5       0.66      0.74      0.70       143
           6       0.61      0.63      0.62       146
           7       0.59      0.41      0.49        41
           8       0.00      0.00      0.00         4

    accuracy                           0.63       343
   macro avg       0.37      0.36      0.36       343
weighted avg       0.60      0.63      0.61       343

[[  0   6   3   0   0]
 [  1 106  34   2   0]
 [  0  46  92   8   0]
 [  0   3  21  17   0]
 [  0   0   2   2   0]]


C:\Users\Sneha Rajput\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Sneha Rajput\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Sneha Rajput\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [44]:
pip install xgboost lightgbm


Note: you may need to restart the kernel to use updated packages.


In [45]:
#Gradient Boosting using XGBoost and LightGBM
import xgboost as xgb

In [56]:
# Map the target to a zero-based range
y_mapped = y - y.min()

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y_mapped, test_size=0.2, random_state=42)

# Initialize XGBoost model
xgb_model = xgb.XGBClassifier(objective='multi:softmax', num_class=len(np.unique(y_mapped)))

# Train the model
xgb_model.fit(X_train, y_train)

# Make predictions
y_pred_xgb = xgb_model.predict(X_test)

# Reverse the mapping of predictions
y_pred_xgb_original = y_pred_xgb + y.min()

# Evaluate performance
accuracy_xgb = accuracy_score(y_test + y.min(), y_pred_xgb_original)
print(f'XGBoost Accuracy: {accuracy_xgb:.4f}')


XGBoost Accuracy: 0.6681


In [52]:
import lightgbm as lgb
from sklearn.metrics import accuracy_score

# Initialize LightGBM model
lgb_model = lgb.LGBMClassifier(objective='multiclass', num_class=len(np.unique(y)))

# Train the model
lgb_model.fit(X_train, y_train)

# Make predictions
y_pred_lgb = lgb_model.predict(X_test)

# Evaluate performance
accuracy_lgb = accuracy_score(y_test, y_pred_lgb)
print(f'LightGBM Accuracy: {accuracy_lgb:.2f}')


[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000224 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1215
[LightGBM] [Info] Number of data points in the train set: 914, number of used features: 12
[LightGBM] [Info] Start training from score -5.026071
[LightGBM] [Info] Start training from score -3.521994
[LightGBM] [Info] Start training from score -0.859406
[LightGBM] [Info] Start training from score -0.923428
[LightGBM] [Info] Start training from score -2.055657
[LightGBM] [Info] Start training from score -4.178773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM

In [6]:
# Assuming you have stored the accuracy for each model in variables
knn_accuracy = 0.54  # Example values, replace with actual results
svm_accuracy = 0.60
rf_accuracy = 0.65
lr_accuracy = 0.63
lgb_accuracy=0.68
xgb_accuracy=0.6681

# Store the accuracies in a dictionary
accuracies = {
    'KNN': knn_accuracy,
    'SVM': svm_accuracy,
    'Random Forest': rf_accuracy,
    'LightGBM Accuracy': lgb_accuracy,
    'Logistic Regression': lr_accuracy,
    'XGBoost Accuracy':xgb_accuracy
}

# Find the best algorithm
best_algorithm = max(accuracies, key=accuracies.get)
best_accuracy = accuracies[best_algorithm]

print(f"The best algorithm is {best_algorithm} with an accuracy of {best_accuracy:.2f}")

The best algorithm is LightGBM Accuracy with an accuracy of 0.68
